# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-27 18:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexo', models.BooleanField(default=True)),
                ('id_persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='id_persona', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
